#cloud-config
runcmd:
  - sudo apt update -y
  - sudo git clone https://github.com/manita711/xalts-assignment.git
  - sudo apt install docker.io -y
  - sudo service docker start 
  - sudo docker build -t my-flask-api /xalts-assignment/
  - sudo docker run -d -p 5000:5000 my-flask-api
